default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: simple_blog
  username: postgres
  password: postgres
  pool: 5

test:
  <<: *default
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  database: simple_blog_test
  username: postgres
  password: postgres
  pool: 5

production:
  <<: *default
  url: <%= ENV['DATABASE'] %>
